### ISSUE TITLE
login ไม่จำ user

### ISSUE THREAD

**Issue by venomm416** [sertjerm/loanshare2024#3]
**ทดสอบ Issues**

**Comment by sertjerm** [comment]
ยังไม่ได้ทำ

**Comment by sertjerm** [comment]
เอาไว้ก่อนนะ

**Comment by sertjerm** [comment]
เรือ่งมากจริง

**Comment by sertjerm** [comment]
closed

**Comment by sertjerm** [comment]
closed 2

**Comment by venomm416** [comment]
test

**Comment by venomm416** [comment]
- [ ] To do1
- [ ] To do2

**Comment by sertjerm** [comment]
- [ ] ทดสอบ 1
- [ ] test 1

**Comment by venomm416** [comment]
> * [x]  ทดสอบ 1
> * [ ]  test 1

ทำไมติ๊กไม่ได้

**Comment by sertjerm** [comment]
<h4>test</h4>

**Comment by sertjerm** [comment]
<h1>test h1</h1>

**Comment by sertjerm** [comment]
**วิธีติดตั้้ง jQuery**

> npm i --save jquery@latest

**Comment by sertjerm** [comment]
@[`test`]www.google.com)
@venomm416

**Comment by venomm416** [comment]
<img width="352" alt="image" src="https://github.com/sertjerm/loanshare2024/assets/102879482/5ce84899-86d5-4cfa-9225-fe12f0d0bda7">

**Comment by venomm416** [comment]
![Uploading image.png…]()
